### ISSUE TITLE
Rename binaries

### ISSUE THREAD

**Issue by voxik** [ruby/xmlrpc#1]
Would you mind to rename the binaries shipped by XMLRPC gem? Both `console` as well as `setup` are so generic, that there is not obvious relation to XMLRPC and what is worse, they will certainly conflict with other binaries. These are conflicting binaries on my Fedora Rawhide:

```
# dnf whatprovides /usr/bin/console
Last metadata expiration check: 1:16:11 ago on Fri May 27 16:14:22 2016.
conserver-client-8.2.1-3.fc24.x86_64 : Serial console client
Repo        : rawhide
```

```
# dnf whatprovides /usr/bin/setup
Last metadata expiration check: 1:16:18 ago on Fri May 27 16:14:22 2016.
setuptool-1.19.11-11.fc24.x86_64 : A text mode system configuration tool
Repo        : @System

setuptool-1.19.11-11.fc24.x86_64 : A text mode system configuration tool
Repo        : rawhide
```

**Comment by voxik** [comment]
Actually looking at .gemspec, they are not treated as executables, but then they are not on conventional place ... I'd expect the real executables under the `bin` directory.

**Comment by hsbt** [comment]
`bin/console` and `bin/setup` are only development usage. It's new convention of bundler template. Please ignore these files.

**Comment by voxik** [comment]
Ok, I will ;) Thx
