### ISSUE TITLE
Possibility for calling method on nil in client

### ISSUE THREAD

**Issue by herwinw** [ruby/xmlrpc#25]
The method `do_rpc` in the client has the following check for content-length, currently line 529-532:
```ruby
# data is set to resp.body a few lines earlier

expected = resp["Content-Length"] || "<unknown>"
if data.nil? or data.bytesize == 0
  raise "Wrong size. Was #{data.bytesize}, should be #{expected}"
end
```

If `data` equals `nil`, this would try to call `bytesize` on it, resulting in a `NoMethodError`. This makes the error very confusing.

Since `data.nil?` is a scenario that should not happen, and is pretty much distinct from an invalid content-length, I guess the best option would be to add a specific check for `data.nil?` after the assignment of `data`, throw a specific error if that happens, and the rest of the code can safely assume `data` is not `nil`.

**Comment by kou** [comment]
Thanks for your report.
Fixed.
