### ISSUE TITLE
Example code in the README does not work anymore

### ISSUE THREAD

**Issue by herwinw** [ruby/xmlrpc#49]
```ruby
server = XMLRPC::Client.new2("http://xmlrpc-c.sourceforge.net/api/sample.php")
result = server.call("sample.sumAndDifference", 5, 3)
```
It looks like sourceforge has had some updates, this URL now redirects to `https://xmlrpc-c.sourceforge.io/api/sample.php` which is just a plain HTML page with no apparent XMLRPC endpoint.

I was unable to find any alternative public XMLRPC server (every site related to XMLRPC seems to be long abandoned by now). If somebody has a suggestion for a public server, that would be the easy fix. Otherwise, it's probably best to just change it to `http://localhost:8080/` or something like that to indicate that you need to run the server yourself to make this work.

**Comment by kou** [comment]
Oh...

> Otherwise, it's probably best to just change it to http://localhost:8080/ or something like that to indicate that you need to run the server yourself to make this work.

It makes sense.
